export GPG_TTY=$TTY

eval "$(/opt/homebrew/bin/brew shellenv)"
autoload -Uz compinit
compinit -d $HOME/.local/zsh/zcompdump

export HISTFILE=$HOME/.local/zsh/zsh_history
export PYENV_ROOT=$HOME/.local/pyenv
export CARGO_HOME=$HOME/.local/rust/cargo
export RUSTUP_HOME=$HOME/.local/rust/rustup
export SWIFTLY_HOME_DIR=$HOME/.local/swiftly
export SWIFTLY_BIN_DIR=$SWIFTLY_HOME_DIR/bin
export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

export LESSHISTFILE=-
export HOMEBREW_NO_ENV_HINTS=1
export HISTORY_SUBSTRING_SEARCH_FUZZY=1

export PATH=$PATH:$PYENV_ROOT/bin:$RUSTUP_HOME/toolchains/stable-aarch64-apple-darwin/bin:$SWIFTLY_BIN_DIR:/Library/TeX/texbin

source <(fzf --zsh)
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

eval "$(pyenv init -)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
