export GPG_TTY=$TTY
export HISTFILE=$HOME/.local/zsh/zsh_history
export HISTSIZE=10000
export SAVEHIST=100000
setopt append_history
setopt inc_append_history
export LESSHISTFILE=$HOME/.local/less/lesshst
export ZSH_COMPDUMP=$HOME/.cache/zsh/zcompcache
export _Z_DATA=$HOME/.local/z/z
export GOPATH=$HOME/.local/go
export CARGO_HOME=$HOME/.local/rust/cargo
export RUSTUP_HOME=$HOME/.local/rust/rustup
export EDITOR=nvim
export VISUAL=nvim
export CMAKE_GENERATOR=Ninja
export HISTORY_SUBSTRING_SEARCH_FUZZY=1
export GIT_ADVICE=0

export FZF_DEFAULT_COMMAND="fd --type f --exclude .git --exclude .DS_Store"
export FZF_DEFAULT_OPTS="
--color=fg:#908caa,fg+:#d0d0d0,bg:-1,bg+:#262626,hl:#ebbcba,hl+:#5fd7ff,info:#9ccfd8,marker:#eb6f92,prompt:#908caa,spinner:#f6c177,pointer:#c4a7e7,header:#31748f,gutter:#191724,border:#403d52,label:#aeaeae,query:#d9d9d9
--height 25% --info right --layout reverse --border rounded --border-label '' --preview-window border-rounded --prompt '❯ ' --marker '*' --pointer '>' --separator '─' --scrollbar '│'
"

case $(uname) in
    Darwin)
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export SWIFTLY_HOME_DIR=$HOME/.local/swiftly
    export SWIFTLY_BIN_DIR=$SWIFTLY_HOME_DIR/bin
    export SWIFTLY_TOOLCHAINS_DIR="$HOME/Library/Developer/Toolchains"
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    export HOMEBREW_NO_ENV_HINTS=1

    export PATH="/opt/homebrew/bin:\
/opt/homebrew/sbin:\
$(brew --prefix llvm)/bin:\
/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/sbin:\
/sbin:\
$GOPATH/bin:\
$(brew --prefix rustup)/bin:\
$SWIFTLY_BIN_DIR:\
/Library/TeX/texbin:\
/System/Cryptexes/App/usr/bin:\
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:\
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:\
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:\
/Library/Apple/usr/bin"

    . <(fzf --zsh)
    . $(brew --prefix)/etc/profile.d/z.sh
    . $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    . $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    . $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh

    alias mls="ls -AFGhot"
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    ;;
    Linux)
    if uwsm check may-start > /dev/null 2>&1; then
        exec uwsm start hyprland
    fi

    export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
    . <(fzf --zsh)
    . /usr/share/z/z.sh
    . /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    . /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    . /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

    alias zed="zeditor"
    alias mls="ls -AFhot --color=always"
    ;;
esac

unalias z
nav() {
    local dir=$(_z 2>&1 | fzf --nth 2.. --tac --no-sort --query "$1" --accept-nth 2..)
    [ -n "$dir" ] && cd "$dir"
}

bindkey -v
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

autoload -Uz compinit
compinit -d $HOME/.local/zsh/zcompdump
eval "$(starship init zsh)"