export GPG_TTY=$TTY
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

export HISTFILE=$XDG_STATE_HOME/zsh/zsh_history
export HISTSIZE=10000
export SAVEHIST=100000
setopt append_history
setopt inc_append_history
setopt notify
unsetopt beep
zstyle :compinstall filename $HOME/.zshrc
zstyle ':completion:*' cache-path $XDG_CACHE_HOME/zcompcache

export LESSHISTFILE=$XDG_STATE_HOME/less/lesshist
export HISTORY_SUBSTRING_SEARCH_FUZZY=1
export _ZO_DATA_DIR=$XDG_STATE_HOME/zoxide
export _ZO_RESOLVE_SYMLINKS=1
export GOPATH=$XDG_DATA_HOME/go
export CMAKE_GENERATOR="Ninja Multi-Config"
export CMAKE_BUILD_PARALLEL_LEVEL=12
export CTEST_PARALLEL_LEVEL=12
export CARGO_HOME=$XDG_DATA_HOME/rust/cargo
export RUSTUP_HOME=$XDG_DATA_HOME/rust/rustup
export GHCUP_USE_XDG_DIRS=1
export EDITOR=nvim
export VISUAL=zed

eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_BUNDLE_NO_DESCRIBE=1
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=7
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=7
export HOMEBREW_MAKE_JOBS=12
export HOMEBREW_NO_UPGRADE_AUTO_UPDATES_CASKS=1
export HOMEBREW_VERBOSE=1

export PATH="/opt/homebrew/bin:\
/opt/homebrew/sbin:\
$HOME/.local/bin:\
$(brew --prefix llvm)/bin:\
$GOPATH/bin:\
$(brew --prefix rustup)/bin:\
/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/sbin:\
/sbin:\
/Library/TeX/texbin:\
/System/Cryptexes/App/usr/bin:\
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:\
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:\
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:\
/Library/Apple/usr/bin"

FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
export PKG_CONFIG_PATH="$(brew --prefix)/lib/pkgconfig"
export CC=$(brew --prefix llvm)/bin/clang
export CXX=$(brew --prefix llvm)/bin/clang++

. $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
. $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
. $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey -v
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

export FZF_DEFAULT_COMMAND="fd --type f --exclude .git --exclude .DS_Store"
export FZF_DEFAULT_OPTS="\
--color=fg:#908caa,fg+:#d0d0d0,bg:-1,bg+:#262626,hl:#ebbcba,hl+:#5fd7ff,info:#9ccfd8,marker:#eb6f92,prompt:#908caa,spinner:#f6c177,pointer:#c4a7e7,header:#31748f,gutter:-1,border:#403d52,label:#aeaeae,query:#d9d9d9 \
--height 25% --info right --layout reverse --border rounded --border-label '' --preview-window border-rounded --prompt '; ' --marker '*' --pointer '>' --separator '─' --scrollbar '│' --gutter ' '\
"
eval "$(zoxide init zsh --no-cmd)"
. <(fzf --zsh)
nav() {
    local dir=$(zoxide query --list --score | fzf --border-label 'navigate to directory' --with-nth 2.. --no-sort --query "$*" --accept-nth 2..)
    [ -n "$dir" ] && cd "$dir"
}

alias mls="ls -AFGhot"
alias mtree="tree -aFC -I .git/ -I .DS_Store"

autoload -Uz compinit
compinit -d $XDG_STATE_HOME/zsh/zcompdump
eval "$(starship init zsh)"