schemaVersion = 4

[catalogConfiguration]
customFolders = []
customItems = []
scriptsDirectories = []

    [[catalogConfiguration.folderDepthOverrides]]
    catalogIdentifier = 'TunaAutomation.ScriptsCatalog'
    depthRawValue = 0

[catalogs]
searchPriorities = []
sortOrders = []

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.effects'

        [catalogs.globalScopes.scope]
        kind = 'none'

    [[catalogs.globalScopes]]
    catalogIdentifier = 'tuna.emoji'

        [catalogs.globalScopes.scope]
        kind = 'none'

[[comboMode.bindings]]
key = 'b'
url = 'tuna://run?subject=tuna.applications//Applications/Zen.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'o'
url = 'tuna://run?subject=tuna.applications//Applications/Obsidian.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 't'
url = 'tuna://run?subject=tuna.applications//Applications/Ghostty.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'e'
url = 'tuna://run?subject=tuna.applications//Applications/Zed.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'm'

    [[comboMode.bindings.children]]
    key = 'm'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Music.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 't'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Messages.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'c'
    url = 'tuna://run?subject=tuna.applications//System/Applications/FaceTime.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'b'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Books.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'h'

    [[comboMode.bindings.children]]
    key = 'c'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Calendar.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'm'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Mail.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 's'
    url = 'tuna://run?subject=tuna.applications//System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'l'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Maps.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'p'

    [[comboMode.bindings.children]]
    key = 'a'
    url = 'tuna://run?subject=tuna.applications//Applications/Andante.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'f'
    url = 'tuna://run?subject=tuna.applications//Applications/forScore.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'v'
    url = 'tuna://run?subject=tuna.applications//System/Applications/VoiceMemos.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = ','

    [[comboMode.bindings.children]]
    key = 's'
    url = 'tuna://run?subject=tuna.applications//System/Applications/System%20Settings.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'f'
    url = 'tuna://run?subject=tuna.applications//System/Library/CoreServices/Finder.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'p'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Passwords.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'l'
    url = 'tuna://run?subject=tuna.applications//Applications/logioptionsplus.app&action=tuna.common-actions/open'

[[comboMode.bindings]]
key = 'a'

    [[comboMode.bindings.children]]
    key = 't'
    url = 'tuna://run?subject=text:/bin/zsh%20~/dev/envy/scripts/toggle-audio.sh&action=tuna.common-actions/run-text-as-shell-command'

    [[comboMode.bindings.children]]
    key = 'm'
    url = 'tuna://run?subject=tuna.applications//System/Applications/Utilities/Audio%20MIDI%20Setup.app&action=Open'

[[comboMode.bindings]]
key = 'w'

    [[comboMode.bindings.children]]
    key = 't'
    url = 'tuna://run?subject=text:/bin/zsh%20~/dev/envy/scripts/toggle-wm.sh&action=tuna.common-actions/run-text-as-shell-command'

    [[comboMode.bindings.children]]
    key = 'f'
    url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20layout%20floating%20tiling&action=tuna.common-actions/run-text-as-shell-command'

    [[comboMode.bindings.children]]
    key = 'j'

        [[comboMode.bindings.children.children]]
        key = 'h'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20join-with%20left&action=tuna.common-actions/run-text-as-shell-command'

        [[comboMode.bindings.children.children]]
        key = 'j'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20join-with%20down&action=tuna.common-actions/run-text-as-shell-command'

        [[comboMode.bindings.children.children]]
        key = 'k'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20join-with%20up&action=tuna.common-actions/run-text-as-shell-command'

        [[comboMode.bindings.children.children]]
        key = 'l'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20join-with%20right&action=tuna.common-actions/run-text-as-shell-command'

    [[comboMode.bindings.children]]
    key = 'd'

        [[comboMode.bindings.children.children]]
        key = 'n'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20move-workspace-to-monitor%20next&action=tuna.common-actions/run-text-as-shell-command'

        [[comboMode.bindings.children.children]]
        key = 'p'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20move-workspace-to-monitor%20prev&action=tuna.common-actions/run-text-as-shell-command'

    [[comboMode.bindings.children]]
    key = 'r'

        [[comboMode.bindings.children.children]]
        key = '['
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20resize%20smart%20-4&action=tuna.common-actions/run-text-as-shell-command'

        [[comboMode.bindings.children.children]]
        key = ']'
        url = 'tuna://run?subject=text:/opt/homebrew/bin/aerospace%20resize%20smart%20+4&action=tuna.common-actions/run-text-as-shell-command'

[[comboMode.bindings]]
key = 'g'

    [[comboMode.bindings.children]]
    key = 'd'
    url = 'tuna://run?subject=tuna.applications//Applications/Discord.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 's'
    url = 'tuna://run?subject=tuna.applications//Applications/Steam.app&action=tuna.common-actions/open'

    [[comboMode.bindings.children]]
    key = 'p'
    url = 'tuna://run?subject=tuna.applications//Applications/Prism%20Launcher.app&action=tuna.common-actions/open'

[hotkeys]
custom = []

    [hotkeys.app.comboMode]
    carbonKeyCode = 49
    carbonModifiers = 256

[settings]
activationDoublePressTrigger = 'leftCommand'
appPresentationMode = 'never'
catalogPeriodicRescanIntervalMinutes = 60
comboModeCheatsheetBehavior = 'never'
comboModeCheatsheetShowDetails = false
comboModeCheatsheetShowIcons = false
comboModeModifierConfiguration = 'optionGroupControlSticky'
comboModeModifierTrigger = 'rightCommand'
fuzzyModeTriggerType = 'doublePress'
screenPreference = 'activeWindow'
shelfCatalogEnabled = false
shelfWindowAlwaysOnTop = false
shortcutDisplayUsesHyperSymbol = false
showTasksIndicatorWhenHidden = false
talkModeTriggerType = 'disabled'
textModeTriggerType = 'disabled'
typingTimeoutDuration = 3.0

[smartLinks]
entries = []

[[catalogSettings]]
catalogIdentifier = 'TunaCore.TextActionsCatalog'

    [catalogSettings.values]
    TextActionsFileExtension = 'txt'

[[catalogSettings]]
catalogIdentifier = 'TunaSystem.WindowManagementCatalog'

    [catalogSettings.values]
    Gap = '8'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'

[[catalogSettings]]
catalogIdentifier = 'tuna.prompts'

    [catalogSettings.values]
    Provider = 'apple'
