after-startup-command = 'exec-and-forget borders'
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focus-changed = 'move-mouse window-lazy-center'
automatically-unhide-macos-hidden-apps = true

accordion-padding = 15
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout v_accordion'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-shift-f = 'fullscreen'

alt-shift-leftSquareBracket = 'resize smart -20'
alt-shift-rightSquareBracket = 'resize smart +20'

alt-q = 'workspace 0'
alt-w = 'workspace 1'
alt-e = 'workspace 2'
alt-r = 'workspace 3'
alt-t = 'workspace 4'
alt-y = 'workspace 5'
alt-u = 'workspace 6'
alt-i = 'workspace 7'
alt-o = 'workspace 8'
alt-p = 'workspace 9'

alt-shift-q = 'move-node-to-workspace 0'
alt-shift-w = 'move-node-to-workspace 1'
alt-shift-e = 'move-node-to-workspace 2'
alt-shift-r = 'move-node-to-workspace 3'
alt-shift-t = 'move-node-to-workspace 4'
alt-shift-y = 'move-node-to-workspace 5'
alt-shift-u = 'move-node-to-workspace 6'
alt-shift-i = 'move-node-to-workspace 7'
alt-shift-o = 'move-node-to-workspace 8'
alt-shift-p = 'move-node-to-workspace 9'

# alt-tab = 'workspace-back-and-forth'
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
f = ['layout floating tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'com.mgsdevelopment.forscore'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.Photos'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'company.thebrowser.dia'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace 7'

