#:schema https://starship.rs/config-schema.json
palette = 'rose-pine'

format = """
${username}${hostname} \
$directory \
$git_branch \
$cmd_duration \
$line_break\
$character
"""

right_format = """
$golang \
$lua \
$python
$zig \
$rust
"""

[directory]
style = 'pine'
format = '[$path]($style)'
truncation_length = 0
truncate_to_repo = false

[git_branch]
style = 'iris'
format = 'on [$branch(:$remote_branch)]($style)'

[cmd_duration]
style = 'highlight_med'
format = '[$duration]($style)'
min_time = 0
show_milliseconds = true

[username]
show_always = true
style_user = 'foam'
format = '[$user]($style)'

[hostname]
ssh_only = false
style = 'foam'
format = '[@$hostname]($style)'

[character]
success_symbol = '[;](foam)'
error_symbol = '[;](love)'

[golang]
style = 'rose'
version_format = '${raw}'
format = '[golang:$version]($style)'

[lua]
style = 'rose'
version_format = '${raw}'
format = '[lua-$version]($style)'

[python]
style = 'rose'
version_format = '${raw}'
python_binary = [["python3"], ["python"]]
format = '[python-$version(-\($virtualenv\))]($style)'

[zig]
style = 'rose'
version_format = '${raw}'
format = '[zig-$version]($style)'

[rust]
style = 'rose'
version_format = '${raw}'
format = '[rust-$version]($style)'

[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'