#:schema https://starship.rs/config-schema.json
palette = 'rose-pine'

format = """
$sudo\
$username\
$hostname \
$directory \
$git_branch \
$cmd_duration\
$line_break\
$character
"""

right_format = """
$time\
$golang\
$lua\
$python\
$zig\
$rust\
$c\
$cpp
"""

[sudo]
disabled = false
format = '[!](gold)'

[username]
show_always = true
format = '[$user](foam)'

[hostname]
ssh_only = false
format = '[@$hostname](foam)'

[directory]
truncation_length = 0
truncate_to_repo = false
format = '[$path](pine)'

[git_branch]
format = 'on [$branch(:$remote_branch)](iris)'

[cmd_duration]
min_time = 0
show_milliseconds = true
format = '[$duration](highlight_med)'

[character]
success_symbol = '[;](foam)'
error_symbol = '[;](love)'

[time]
disabled = false
format = '[$time](highlight_med)'

[golang]
version_format = '${raw}'
format = '[ golang:$version](rose)'

[lua]
version_format = '${raw}'
format = '[ lua:$version](rose)'

[python]
python_binary = [["python3"], ["python"]]
version_format = '${raw}'
format = '[ python:$version(-\($virtualenv\))](rose)'

[zig]
version_format = '${raw}'
format = '[ zig:$version](rose)'

[rust]
version_format = '${raw}'
format = '[ rust:$version](rose)'

[c]
commands = [
    [
        "/opt/homebrew/opt/llvm/bin/clang",
        "--version",
    ],
    [
        "clang",
        "--version",
    ],
]
version_format = '${raw}'
format = '[ c:$name$version](rose)'

[cpp]
version_format = '${raw}'
format = '[ c++:$name$version](rose)'


[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'